'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Desarrollo.Domain.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM  Client 
        '''WHERE Id = {Id}.
        '''</summary>
        Friend ReadOnly Property ClientDelete() As String
            Get
                Return ResourceManager.GetString("ClientDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT 
        '''	Id,
        '''    Nombre,
        '''    DiasPago,
        '''    Temperatura,
        '''    Flete,
        '''    Tipo,
        '''    Porcentaje,
        '''    Absoluto,
        '''    ProviderId
        '''FROM Client.
        '''</summary>
        Friend ReadOnly Property ClientGett() As String
            Get
                Return ResourceManager.GetString("ClientGett", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT 
        '''	Id,
        '''    Nombre,
        '''    DiasPago,
        '''    Temperatura,
        '''    Flete,
        '''    Tipo,
        '''    Porcentaje,
        '''    Absoluto,
        '''    ProviderId
        '''FROM Client
        '''Where Id = {Id}.
        '''</summary>
        Friend ReadOnly Property ClientGettById() As String
            Get
                Return ResourceManager.GetString("ClientGettById", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EXEC SelectAllClient;.
        '''</summary>
        Friend ReadOnly Property ClientGettProc() As String
            Get
                Return ResourceManager.GetString("ClientGettProc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO Client 
        '''    (Nombre,
        '''     DiasPago,
        '''     Temperatura,
        '''     Flete,
        '''     Tipo,
        '''     Porcentaje,
        '''     Absoluto,
        '''     ProviderId)
        '''VALUES(
        '''    &apos;{Nombre}&apos;,
        '''    {DiasPago},
        '''    {Temperatura},
        '''    {Flete},
        '''    {Tipo},
        '''    {Porcentaje},
        '''    &apos;{Absoluto}&apos;,
        '''    {ProviderId}).
        '''</summary>
        Friend ReadOnly Property ClientInsert() As String
            Get
                Return ResourceManager.GetString("ClientInsert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE Cliente 
        '''    SET 
        '''        Nombre = &apos;{Nombre}&apos;,
        '''        DiasPago = {DiasPago},
        '''        Temperatura = {Temperatura},
        '''        Flete = {Flete},
        '''        Tipo = {Tipo},
        '''        Porcentaje = {Porcentaje},
        '''        Absoluto = &apos;{Absoluto}&apos;,
        '''        ProviderId = {ProviderId}
        '''WHERE Id = {Id}.
        '''</summary>
        Friend ReadOnly Property ClientUpdate() As String
            Get
                Return ResourceManager.GetString("ClientUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM  Contact 
        '''WHERE Id = {Id}.
        '''</summary>
        Friend ReadOnly Property ContactDelete() As String
            Get
                Return ResourceManager.GetString("ContactDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT 
        '''	Id,
        '''    Nombre,
        '''    Departamento,
        '''    Email,
        '''    Telefono,
        '''    ProviderId
        '''FROM Contact.
        '''</summary>
        Friend ReadOnly Property ContactGett() As String
            Get
                Return ResourceManager.GetString("ContactGett", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT 
        '''	Id,
        '''    Nombre,
        '''    Departamento,
        '''    Email,
        '''    Telefono,
        '''    ProviderId
        '''FROM Contact
        '''Where Id = {Id}.
        '''</summary>
        Friend ReadOnly Property ContactGettById() As String
            Get
                Return ResourceManager.GetString("ContactGettById", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO Contact 
        '''    (Nombre,
        '''    Departamento,
        '''    Email,
        '''    Telefono,
        '''    ProviderId)
        '''VALUES(
        '''    &apos;{Nombre}&apos;,
        '''    &apos;{Departamento}&apos;,
        '''    &apos;{Email}&apos;,
        '''    &apos;{Telefono}&apos;,
        '''    {ProviderId}).
        '''</summary>
        Friend ReadOnly Property ContactInsert() As String
            Get
                Return ResourceManager.GetString("ContactInsert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE Contact 
        '''    SET 
        '''        Nombre = &apos;{Nombre}&apos;,
        '''        Departamento = &apos;{Departamento}&apos;,
        '''        Email = &apos;{Email}&apos;,
        '''        Telefono = &apos;{Telefono}&apos;,
        '''        ProviderId = {ProviderId},
        '''WHERE Id = {Id}.
        '''</summary>
        Friend ReadOnly Property ContactUpdate() As String
            Get
                Return ResourceManager.GetString("ContactUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT 
        '''	Id,
        '''    Nombre,
        '''    DiasPago,
        '''    Temperatura,
        '''    Flete,
        '''    Tipo,
        '''    Porcentaje,
        '''    Absoluto,
        '''    ProviderId
        '''FROM Client
        '''Where ProviderId = {Id}.
        '''</summary>
        Friend ReadOnly Property GettClientByProviderId() As String
            Get
                Return ResourceManager.GetString("GettClientByProviderId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT 
        '''	Id,
        '''    Nombre,
        '''    Departamento,
        '''    Email,
        '''    Telefono,
        '''    ProviderId
        '''FROM Contact
        '''Where ProviderId = {Id}.
        '''</summary>
        Friend ReadOnly Property GettContactByProviderId() As String
            Get
                Return ResourceManager.GetString("GettContactByProviderId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT 
        '''	Id,
        '''    ClientId,
        '''    VolumeComprometido,
        '''    Desde,
        '''    Hasta
        '''FROM Volume
        '''Where Id = {Id}.
        '''</summary>
        Friend ReadOnly Property GettVolumeByClientId() As String
            Get
                Return ResourceManager.GetString("GettVolumeByClientId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM  Provider 
        '''WHERE Id = {Id}.
        '''</summary>
        Friend ReadOnly Property ProviderDelete() As String
            Get
                Return ResourceManager.GetString("ProviderDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT 
        '''    Id,
        '''    Nombre,
        '''    Direccion,
        '''    Ref
        '''FROM Provider.
        '''</summary>
        Friend ReadOnly Property ProviderGett() As String
            Get
                Return ResourceManager.GetString("ProviderGett", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT 
        '''    Id,
        '''    Nombre,
        '''    Direccion,
        '''    Ref
        '''FROM Provider
        '''Where Id = {Id}.
        '''</summary>
        Friend ReadOnly Property ProviderGettById() As String
            Get
                Return ResourceManager.GetString("ProviderGettById", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO Provider 
        '''    (Nombre,
        '''     Direccion,
        '''     Ref)
        '''VALUES(
        '''    &apos;{Nombre}&apos;,
        '''    &apos;{Direccion}&apos;,
        '''    {Ref}).
        '''</summary>
        Friend ReadOnly Property ProviderInsert() As String
            Get
                Return ResourceManager.GetString("ProviderInsert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE Provider 
        '''    SET Nombre = &apos;{Nombre}&apos;,
        '''     Direccion = &apos;{Direccion}&apos;,
        '''     Ref = {Ref}
        '''WHERE Id = {Id}.
        '''</summary>
        Friend ReadOnly Property ProviderUpdate() As String
            Get
                Return ResourceManager.GetString("ProviderUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM  Volume 
        '''WHERE Id = {Id}.
        '''</summary>
        Friend ReadOnly Property VolumeDelete() As String
            Get
                Return ResourceManager.GetString("VolumeDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT 
        '''	Id,
        '''    ClientId,
        '''    VolumeComprometido,
        '''    Desde,
        '''    Hasta
        '''FROM Volume.
        '''</summary>
        Friend ReadOnly Property VolumeGett() As String
            Get
                Return ResourceManager.GetString("VolumeGett", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT 
        '''	Id,
        '''    ClientId,
        '''    VolumeComprometido,
        '''    Desde,
        '''    Hasta
        '''FROM Volume
        '''Where Id = {Id}.
        '''</summary>
        Friend ReadOnly Property VolumeGettById() As String
            Get
                Return ResourceManager.GetString("VolumeGettById", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO Volume 
        '''    (ClientId,
        '''    VolumeComprometido,
        '''    Desde,
        '''    Hasta)
        '''VALUES(
        '''    {ClientId},
        '''    {VolumeComprometido},
        '''    &apos;{Desde}&apos;,
        '''    &apos;{Hasta}&apos;).
        '''</summary>
        Friend ReadOnly Property VolumeInsert() As String
            Get
                Return ResourceManager.GetString("VolumeInsert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE Volume 
        '''    SET 
        '''        ClientId = {ClientId},
        '''        VolumeComprometido = {VolumeComprometido},
        '''        Desde = &apos;{Desde}&apos;,
        '''        Hasta = &apos;{Hasta}&apos;,
        '''WHERE Id = {Id}.
        '''</summary>
        Friend ReadOnly Property VolumeUpdate() As String
            Get
                Return ResourceManager.GetString("VolumeUpdate", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
